template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: simplehelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: {{ .Values.artifactoryIntegration }}
      repository: simplecharts
      chart: simplehelm
      version: 0.0.0

  - name: simplehelmRepo_chart
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitIntegration }}                      
      path: {{ .Values.gitRepositoryPath }}  
      #files:
      #  include: "simplehelm.*"

  - name: simplehelmRepo_docker
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitIntegration }}                      
      path: {{ .Values.gitRepositoryPath }} 
      #files:
      #  include: "Dockerfile|server.js|package.json"

  - name: simplehelmDockerImage
    type: Image
    configuration:
      registry: myDocker
      imageName:  {{ .Values.artifactoryUrl }}/{{ .Values.sourceRepository }}/{{ .Values.imageName }}
      imageTag: latest

pipelines:
  - name: helm_full_flow
    steps:
       - name: build
         type: DockerBuild
         configuration:
           affinityGroup: buildAndPush
           integrations:
             - name: {{ .Values.artifactoryIntegration }} 
           inputResources:
             - name: simplehelmRepo_docker
           dockerFileLocation: .
           dockerFileName: Dockerfile
           dockerImageName: {{ .Values.artifactoryUrl }}/{{ .Values.sourceRepository }}/{{ .Values.imageName }}
           dockerImageTag: $run_number

       - name: push
         type: DockerPush
         configuration:
           affinityGroup: buildAndPush
           integrations:
             - name: {{ .Values.artifactoryIntegration }} 
           targetRepository: {{ .Values.sourceRepository }}
           inputSteps:
             - name: build
           outputResources:
             - name: simplehelmDockerImage

       - name: publish_helm_chart
         type: HelmPublish
         configuration:
           inputResources:
             - name: simplehelmRepo_chart
           outputResources:
             - name: simplehelmChart
           chartPath: ./chart
         execution:
           onStart:
            - pushd /tmp
            - wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
            - tar -zxvf helm-v2.14.3-linux-amd64.tar.gz
            - mv linux-amd64/helm /usr/local/bin/helm
            - popd

       - name: deploy_helm_chart
         type: HelmDeploy
         configuration:
           integrations:
             - name: myKubernetes
           inputResources:
             - name: simplehelmChart
             - name: simplehelmDockerImage
           releaseName: simplehelm
         execution:
           onStart:
            - pushd /tmp
            - wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
            - tar -zxvf helm-v2.14.3-linux-amd64.tar.gz
            - mv linux-amd64/helm /usr/local/bin/helm
            - popd
